### ISSUE TITLE
RT_Jog_Controller not working

### ISSUE THREAD

**Issue by zab-ig** [Expatria-Technologies/RT_Jog_Controller#10]
Good afternoon.
I assembled the controller and I have some problems. After the firmware of the controller, the LEDs light up in white and the inscription "GRBLHALL I2C JOGGER" appears on the screen. After that, the screen goes blank and nothing else happens, the LEDs continue to glow white.
Tell me what's the problem?

**Comment by jaymis** [comment]
I think you might need to provide some more details @zab-ig 
What Controller are you plugging your Jogger into (Flexi-HAL or GRBLHAL2000)? What cable are you using? What firmware version is running on the Jogger and the Controller?

**Comment by zab-ig** [comment]
I use GRBLGRBLHAL2000 and LAN cable 1 m long. Version firmware Jogger 1.0.2, GRBLHAL2000 V.230529.
If you connect an oscilloscope to the i2с jogger bus, then there are signals on the SСL and SDA lines.
If you supply power to the jogger and do not connect it to the GRBL controller, how should it behave? In my case, the LEDs light up white, an inscription appears on the "GRBLHALL I2C JOGGER" screen, and then the screen goes blank.

**Comment by jaymis** [comment]
That's correct behaviour for the jogger if it's powered but not connected to a controller. It needs to communicate with the controller to do anything else.

**Comment by andrewmarles** [comment]
You need to use exactly the linked branch of the keypad plug-in:

https://github.com/Expatria-Technologies/Plugin_I2C_keypad

This is linked in the read me.  The pre built firmware uses that branch.

https://github.com/Expatria-Technologies/iMXRT1062/releases/tag/v1.05

**Comment by zab-ig** [comment]
Thank you. Everything is working.

**Comment by zab-ig** [comment]
A new problem has arisen.
 If I flash GRBL2000 firmware 1.05, then the Jog_Controller works. But in 1.05 EEPROM is not activated. I downloaded the source https://github.com/Expatria-Technologies/iMXRT1062. In my_machine.h I have activated all the necessary plugins including the KEYPAD_ENABLE. The firmware compiles successfully. After the firmware, the Jog_Controller does not work correctly. The screen displays the coordinates at the moment the Jog_Controller is connected to the GRBL2000, the Jog_Controller does not respond to buttons, the coordinates on the screen do not change. The iosender program lists all enabled plugins except for the keyboard:
%
; grblHAL
; 1.1f.20230129
; [OPT:VNMSL,35,1024,3,0]
; [NEWOPT:ENUMS,RT+,ES,REBOOT,TC,SED,RTC,ETH,ODO]
; [FIRMWARE:grblHAL]
; [NVS STORAGE:*FRAM]
; [DRIVER:iMXRT1062]
; [DRIVER VERSION:230125]
; [DRIVER OPTIONS:USB.2]
; [BOARD:GRBLHAL2000 - PRINTNC]
; [AUX IO:4,1,0,0]
; [IP:]
; [PLUGIN:MODBUS v0.14]
; [PLUGIN:MODVFD v0.03]
; [SPINDLE:PWM]
; [PLUGIN:RGB Indicator Lights v1.0]
; [PLUGIN:ODOMETERS v0.02]

**Comment by andrewmarles** [comment]
Did you install the fram yourself?  That part isn’t on the BoM.  You will need to sort that out if you are using something other than what we built.  The eeprom isn’t used on our builds because it is too small to hold all of the config data from later grblhal versions.
