### ISSUE TITLE
Upside down display.

### ISSUE THREAD

**Issue by hambudi** [Expatria-Technologies/RT_Jog_Controller#15]
I assembled the RT Jog Controller, with the 2k Deluxe enclosure. I attached the LCD screen (upside down as per the instructions on github). 

Now the text on the display is upside down, how do I flip the display orientation?
![IMG_1787](https://github.com/Expatria-Technologies/RT_Jog_Controller/assets/2451823/1505745e-62b4-43a4-a3e8-8613c6879731)

**Comment by andrewmarles** [comment]
https://github.com/Expatria-Technologies/RT_Jog_Controller?tab=readme-ov-file#usage

`The HALT button has an alternate function which is to flip the OLED screen vertically. There is no standard orientation for these screens so if yours is upside-down after installation, simply activate the screen flip. The screen orientation is stored in NVM. The Jog2K should reset automatically around 2s after the command is issued.`
