### ISSUE TITLE
Bottom Enclosure 1.3 slim.stl is the top instead. 

### ISSUE THREAD

**Issue by LoganFraser** [Expatria-Technologies/RT_Jog_Controller#7]
![image](https://user-images.githubusercontent.com/33788254/210125364-8b50fb44-d11b-478e-98e7-7d8dbcd5a111.png)

**Comment by LoganFraser** [comment]
As above, the BottomEnclosure1.3slim.STL is of the top, not the bottom.

**Comment by andrewmarles** [comment]
Fixed.  Thanks very much.
