### ISSUE TITLE
Add "Simplified" sub-directory and its buttons to the Deluxe version's Button sub-directories 

### ISSUE THREAD

**Issue by R-Ronald** [Expatria-Technologies/RT_Jog_Controller#8]
Currently the Deluxe version of the Jog2K uses 9 buttons that are printed in white with black button caps (along with many other buttons that are not relevant to this request). 

I have an alternative set of buttons that use icons designed to be "colored in" using a dark Ultra Fine Point Sharpie. The buttons are simpler and less difficult to print, don't require assembly, and provide better contrast/legibility. 

I have 6 STL files for 3d printing the 9 required buttons. I also have a readme.txt that provides instructions for substituting these buttons for the baseline version and a readme.pdf that includes a picture. All 8 of these files are designed to live a single sub- directory with the tentative name of "Simplified" alongside the White, Black and Clear sub-directories.

Github doesn't seem to allow STL uploads for a pull request, but I have them ready to go. Here are the two readme files:
[readme.txt](https://github.com/Expatria-Technologies/RT_Jog_Controller/files/10404879/readme.txt)
[readme.pdf](https://github.com/Expatria-Technologies/RT_Jog_Controller/files/10404880/readme.pdf)

**Comment by andrewmarles** [comment]
Talking to mikem, it sounds like this got merged into the mods repo.  Cheers.
